export type CardType = {
  fileName: string;
  paintingTitle: string;
  paintingTitleEN: string;
  year: string;
  technique: string;
  techniqueEN: string;
  size: string;
  price: number | undefined;
};

export const dataEphemerally: CardType[] = [
  {
    fileName: "Efemera o jesieni 01",
    paintingTitle: "Efemera o jesieni 01",
    paintingTitleEN: "Ephemera About Autumn 01",
    year: "2022",
    technique: "akwarela na papierze Daler Rowney",
    techniqueEN: "watercolour on Daler Rowney paper",
    size: "29.7x42 cm",
    price: 1200,
  },
  {
    fileName: "Efemera o jesieni 02",
    paintingTitle: "Efemera o jesieni 02",
    paintingTitleEN: "Ephemera About Autumn 02",
    year: "2022",
    technique: "akwarela na papierze Daler Rowney",
    techniqueEN: "watercolour on Daler Rowney paper",
    size: "29.7x42 cm",
    price: 1200,
  },
  {
    fileName: "Efemera o jesieni 03",
    paintingTitle: "Efemera o jesieni 03",
    paintingTitleEN: "Ephemera About Autumn 03",
    year: "2022",
    technique: "akwarela na papierze Daler Rowney",
    techniqueEN: "watercolour on Daler Rowney paper",
    size: "29.7x42 cm",
    price: 1200,
  },
  {
    fileName: "Efemera o lecie",
    paintingTitle: "Efemera o lecie",
    paintingTitleEN: "Ephemera About Summer",
    year: "2021",
    technique: "akwarela na papierze Daler Rowney",
    techniqueEN: "watercolour on Daler Rowney paper",
    size: "29.7x42 cm",
    price: 1200,
  },
  {
    fileName: "Efemera o wiosnie 01",
    paintingTitle: "Efemera o wiośnie 01",
    paintingTitleEN: "Ephemera About Spring 01",
    year: "2022",
    technique: "akwarela na papierze Daler Rowney",
    techniqueEN: "watercolour on Daler Rowney paper",
    size: "29.7x42 cm",
    price: 1200,
  },
  {
    fileName: "Efemera o wiosnie 02",
    paintingTitle: "Efemera o wiośnie 02",
    paintingTitleEN: "Ephemera About Spring 02",
    year: "2022",
    technique: "akwarela na papierze Daler Rowney",
    techniqueEN: "watercolour on Daler Rowney paper",
    size: "29.7x42 cm",
    price: 1200,
  },
  {
    fileName: "Efemera o wiosnie 03",
    paintingTitle: "Efemera o wiośnie 03",
    paintingTitleEN: "Ephemera About Spring 03",
    year: "2022",
    technique: "akwarela na papierze Daler Rowney",
    techniqueEN: "watercolour on Daler Rowney paper",
    size: "29.7x42 cm",
    price: 1200,
  },
];

export const dataPureHappiness: CardType[] = [
  {
    fileName: "Sama szczesciem chwila",
    paintingTitle: "Sama szczęściem chwila",
    paintingTitleEN: "One Happiness A While",
    year: "2023",
    technique: "olej na płótnie",
    techniqueEN: "oil on canvas",
    size: "100x130 cm",
    price: 9500,
  },
  {
    fileName: "Same szczescia bledna",
    paintingTitle: "Same szczęścia bledną",
    paintingTitleEN: "Happinesses Fade Away",
    year: "2022",
    technique: "olej na płótnie",
    techniqueEN: "oil on canvas",
    size: "90x90 cm",
    price: 7500,
  },
  {
    fileName: "Samo szczescie pozniej obecne",
    paintingTitle: "Samo szczęście później obecne",
    paintingTitleEN: "One Happiness That Happens Later",
    year: "2022",
    technique: "olej na płótnie",
    techniqueEN: "oil on canvas",
    size: "130x100 cm",
    price: 9500,
  },
  {
    fileName: "Samym szczesciem dzielenie",
    paintingTitle: "Samym szczęściem dzielenie",
    paintingTitleEN: "Same Happiness To Share",
    year: "2023",
    technique: "olej na płótnie",
    techniqueEN: "oil on canvas",
    size: "100x130 cm",
    price: 9500,
  },
];

export const dataTinySensibility: CardType[] = [
  {
    fileName: "Wrazliwosc zadumy (14)",
    paintingTitle: "Wrażliwość zadumy (14)",
    paintingTitleEN: "Sensibility Of Reverie (14)",
    year: "2022",
    technique: "olej na płótnie",
    techniqueEN: "oil on canvas",
    size: "60x90 cm",
    price: 6000,
  },
  {
    fileName: "Wrazliwosc wzroku (12)",
    paintingTitle: "Wrażliwość wzroku (12)",
    paintingTitleEN: "Sensibility Of Sight (12)",
    year: "2021",
    technique: "olej na płótnie",
    techniqueEN: "oil on canvas",
    size: "90x60 cm",
    price: 6000,
  },
  {
    fileName: "Wrazliwosc zmagan (11)",
    paintingTitle: "Wrażliwość zmagań (11)",
    paintingTitleEN: "Sensibility Of Struggle (11)",
    year: "2022",
    technique: "olej na płótnie",
    techniqueEN: "oil on canvas",
    size: "90x60 cm",
    price: 6000,
  },
  {
    fileName: "Wrazliwosc wlasnego gabarytu (10)",
    paintingTitle: "Wrażliwość własnego gabarytu (10)",
    paintingTitleEN: "Sensibility Of Own Heavyness (10)",
    year: "2020",
    technique: "olej na płótnie",
    techniqueEN: "oil on canvas",
    size: "90x60 cm",
    price: 6000,
  },
  {
    fileName: "Wrazliwosc trudu (9)",
    paintingTitle: "Wrażliwość trudu (9)",
    paintingTitleEN: "Sensibility Of Difficulty (9)",
    year: "2019",
    technique: "olej na płótnie",
    techniqueEN: "oil on canvas",
    size: "90x60 cm",
    price: 6000,
  },
  {
    fileName: "Wrazliwosc ospalosci (8)",
    paintingTitle: "Wrażliwość ospałości (8)",
    paintingTitleEN: "Sensibility Of Lethargy (8)",
    year: "2019",
    technique: "olej na płótnie",
    techniqueEN: "oil on canvas",
    size: "60x90 cm",
    price: 6000,
  },
  {
    fileName: "Wrazliwosc niewygody (7)",
    paintingTitle: "Wrażliwość niewygody (7)",
    paintingTitleEN: "Sensibility Of Comfortless (7)",
    year: "2020",
    technique: "olej na płótnie",
    techniqueEN: "oil on canvas",
    size: "90x60 cm",
    price: 6000,
  },
  {
    fileName: "Wrazliwosc obserwacji (5)",
    paintingTitle: "Wrażliwość obserwacji (5)",
    paintingTitleEN: "Sensibility Of Observation (5)",
    year: "2019",
    technique: "olej na płótnie",
    techniqueEN: "oil on canvas",
    size: "90x60 cm",
    price: 6000,
  },
  {
    fileName: "Wrazliwosc zwiadu (4)",
    paintingTitle: "Wrażliwość zwiadu (4)",
    paintingTitleEN: "Sensibility Of Spying (4)",
    year: "2019",
    technique: "olej na płótnie",
    techniqueEN: "oil on canvas",
    size: "90x60 cm",
    price: 6000,
  },
  {
    fileName: "Wrazliwosc zaskoczenia (2)",
    paintingTitle: "Wrażliwość zaskoczenia (2)",
    paintingTitleEN: "Sensibility Of Surprise (2)",
    year: "2020",
    technique: "olej na płótnie",
    techniqueEN: "oil on canvas",
    size: "60x90 cm",
    price: 6000,
  },
  {
    fileName: "Wrazliwosc blogosci (1)",
    paintingTitle: "Wrażliwość błogości (1)",
    paintingTitleEN: "Sensibility Of Comfort (1)",
    year: "2017",
    technique: "olej na płótnie",
    techniqueEN: "oil on canvas",
    size: "90x60 cm",
    price: 6000,
  },
];

export const dataMeBlindWoman: CardType[] = [
  {
    fileName: "Czerwien koloru ciala (3)",
    paintingTitle: "Czerwień koloru ciała (3)",
    paintingTitleEN: "Red Beige Body (3)",
    year: "2022",
    technique: "olej na płótnie",
    techniqueEN: "oil on canvas",
    size: "90x90 cm",
    price: 11000,
  },
  {
    fileName: "Czerwien koloru ciala (2)",
    paintingTitle: "Czerwień koloru ciała (2)",
    paintingTitleEN: "Red Beige Body (2)",
    year: "2022",
    technique: "olej na płótnie",
    techniqueEN: "oil on canvas",
    size: "90x90 cm",
    price: 11000,
  },
  {
    fileName: "Czerwien koloru ciala (1)",
    paintingTitle: "Czerwień koloru ciała (1)",
    paintingTitleEN: "Red Beige Body (1)",
    year: "2022",
    technique: "olej na płótnie",
    techniqueEN: "oil on canvas",
    size: "90x90 cm",
    price: 11000,
  },
  {
    fileName: "Kobieta 15",
    paintingTitle: "Kobieta 15",
    paintingTitleEN: "Woman 15",
    year: "2022",
    technique: "olej na płótnie",
    techniqueEN: "oil on canvas",
    size: "50x130 cm",
    price: 7000,
  },
  {
    fileName: "Kobieta 14",
    paintingTitle: "Kobieta 14",
    paintingTitleEN: "Woman 14",
    year: "2022",
    technique: "olej na płótnie",
    techniqueEN: "oil on canvas",
    size: "70x130 cm",
    price: 8000,
  },
  {
    fileName: "Kobieta 13",
    paintingTitle: "Kobieta 13",
    paintingTitleEN: "Woman 13",
    year: "2022",
    technique: "olej na płótnie",
    techniqueEN: "oil on canvas",
    size: "70x130 cm",
    price: 8000,
  },
  {
    fileName: "Kobieta 12",
    paintingTitle: "Kobieta 12",
    paintingTitleEN: "Woman 12",
    year: "2022",
    technique: "olej na płótnie",
    techniqueEN: "oil on canvas",
    size: "50x130 cm",
    price: 7000,
  },
  {
    fileName: "Kobieta 11",
    paintingTitle: "Kobieta 11",
    paintingTitleEN: "Woman 11",
    year: "2022",
    technique: "olej na płótnie",
    techniqueEN: "oil on canvas",
    size: "50x130 cm",
    price: 7000,
  },
  {
    fileName: "Kobieta 10",
    paintingTitle: "Kobieta 10",
    paintingTitleEN: "Woman 10",
    year: "2016",
    technique: "olej na płótnie",
    techniqueEN: "oil on canvas",
    size: "100x130 cm",
    price: 9500,
  },
  {
    fileName: "Kobieta 08",
    paintingTitle: "Kobieta 08",
    paintingTitleEN: "Woman 08",
    year: "2016",
    technique: "olej na płótnie",
    techniqueEN: "oil on canvas",
    size: "50x130 cm",
    price: 7000,
  },
  {
    fileName: "Kobieta 07",
    paintingTitle: "Kobieta 07",
    paintingTitleEN: "Woman 07",
    year: "2016",
    technique: "olej na płótnie",
    techniqueEN: "oil on canvas",
    size: "90x130 cm",
    price: 9000,
  },
  {
    fileName: "Kobieta 05",
    paintingTitle: "Kobieta 05",
    paintingTitleEN: "Woman 05",
    year: "2016",
    technique: "olej na płótnie",
    techniqueEN: "oil on canvas",
    size: "70x130 cm",
    price: undefined,
  },
  {
    fileName: "Kobieta 03",
    paintingTitle: "Kobieta 03",
    paintingTitleEN: "Woman 03",
    year: "2016",
    technique: "olej na płótnie",
    techniqueEN: "oil on canvas",
    size: "90x130 cm",
    price: 9000,
  },
  {
    fileName: "Kobieta 02",
    paintingTitle: "Kobieta 02",
    paintingTitleEN: "Woman 02",
    year: "2016",
    technique: "olej na płótnie",
    techniqueEN: "oil on canvas",
    size: "130x130 cm",
    price: 11000,
  },
  {
    fileName: "Kobieta 01",
    paintingTitle: "Kobieta 01",
    paintingTitleEN: "Woman 01",
    year: "2016",
    technique: "olej na płótnie",
    techniqueEN: "oil on canvas",
    size: "130x130 cm",
    price: 11000,
  },
];
